version: "3.8"

services:
  flask_app:
    build:
      context: .
    ports:
      - "5001:5000"  # Mudei a porta interna para evitar conflitos
    environment:
      - FLASK_ENV=production
    depends_on:
      - logstash
    command: ["flask", "run", "--host=0.0.0.0"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.0
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.0
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: ["filebeat", "-e", "-strict.perms=false"]
    depends_on:
      - logstash

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
